### ISSUE TITLE
Party grid is not updated correctly when people join, while I'm in combat

### ISSUE THREAD

**Issue by razor101** [blooblahguy/bdGrid#9]
As the title says. To re-produce: fight a mob, like for a world quest, and start a group that auto-accepts people, and see how the Party Grid is not updating (no squares appear) as people join.

**Comment by gladelynch** [comment]
This is actually blizzard functionality :(. Once you leave combat, the frames should appear correctly. This happens for the default blizzard raid frames as well. They just have to be created once outside of combat to be used.
